<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Resident registration | Southville Phase I HOA</title>@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
<body><main class="auth-shell"><section class="auth-card" aria-labelledby="register-title">
    <a class="auth-brand" href="{{ route('home') }}"><span class="brand-mark" aria-hidden="true">S1</span>Southville Phase I</a>
    <h1 id="register-title">Resident registration</h1><p>Your application will be reviewed by the HOA Admin before portal access is activated.</p>
    @if($errors->any())<div class="error-summary" role="alert" tabindex="-1"><strong>Please correct the following:</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form method="POST" action="{{ route('portal.register.store') }}" data-review-registration>@csrf
        <div class="form-grid two">
            @php($fields = ['first_name' => 'First name', 'middle_name' => 'Middle name', 'last_name' => 'Last name', 'house_number' => 'House number', 'street' => 'Street', 'block' => 'Block', 'lot' => 'Lot'])
            @foreach($fields as $name => $label)<div class="field"><label for="{{ $name }}">{{ $label }} @if(in_array($name, ['first_name','last_name','house_number','street','block','lot']))<span aria-hidden="true">*</span>@endif</label><input id="{{ $name }}" name="{{ $name }}" value="{{ old($name) }}" @if(in_array($name, ['first_name','last_name','house_number','street','block','lot'])) required @endif maxlength="100" @error($name) aria-invalid="true" aria-describedby="{{ $name }}-error" @enderror>@error($name)<p id="{{ $name }}-error" class="error">{{ $message }}</p>@enderror</div>@endforeach
            <div class="field"><label for="suffix">Suffix</label><select id="suffix" name="suffix"><option value="">None</option>@foreach(['Jr.','Sr.','II','III','IV'] as $value)<option @selected(old('suffix') === $value)>{{ $value }}</option>@endforeach</select></div>
            <div class="field"><label for="sex">Sex <span aria-hidden="true">*</span></label><select id="sex" name="sex" required>@foreach(['Male','Female','Prefer not to say'] as $value)<option value="{{ $value }}" @selected(old('sex') === $value)>{{ $value }}</option>@endforeach</select></div>
            <div class="field"><label for="date_of_birth">Date of birth <span aria-hidden="true">*</span></label><input id="date_of_birth" name="date_of_birth" type="date" value="{{ old('date_of_birth') }}" max="{{ now()->subDay()->toDateString() }}" required autocomplete="bday">@error('date_of_birth')<p class="error">{{ $message }}</p>@enderror</div>
            <div class="field"><label for="contact_number">Contact number <span aria-hidden="true">*</span></label><input id="contact_number" name="contact_number" inputmode="numeric" pattern="09[0-9]{9}" maxlength="11" value="{{ old('contact_number') }}" required autocomplete="tel" aria-describedby="contact-hint"><p id="contact-hint" class="hint">Use an 11-digit Philippine mobile number beginning with 09.</p>@error('contact_number')<p class="error">{{ $message }}</p>@enderror</div>
            <div class="field"><label for="residency_date">Residency date <span aria-hidden="true">*</span></label><input id="residency_date" name="residency_date" type="date" value="{{ old('residency_date') }}" max="{{ today()->toDateString() }}" required>@error('residency_date')<p class="error">{{ $message }}</p>@enderror</div>
            <div class="field"><label for="ownership_type">Ownership type <span aria-hidden="true">*</span></label><select id="ownership_type" name="ownership_type" required>@foreach(['Owner','Tenant','Co-owner'] as $value)<option @selected(old('ownership_type') === $value)>{{ $value }}</option>@endforeach</select></div>
            <div class="field"><label for="email">Email address <span aria-hidden="true">*</span></label><input id="email" name="email" type="email" value="{{ old('email') }}" required autocomplete="email">@error('email')<p class="error">{{ $message }}</p>@enderror</div>
            <div class="field"><label for="password">Password <span aria-hidden="true">*</span></label><input id="password" name="password" type="password" required autocomplete="new-password" aria-describedby="password-hint"><button type="button" class="link-button" data-password-toggle="password" aria-pressed="false">Show password</button><p id="password-hint" class="hint">At least 12 characters with letters and numbers.</p>@error('password')<p class="error">{{ $message }}</p>@enderror</div>
            <div class="field"><label for="password_confirmation">Confirm password <span aria-hidden="true">*</span></label><input id="password_confirmation" name="password_confirmation" type="password" required autocomplete="new-password"><button type="button" class="link-button" data-password-toggle="password_confirmation" aria-pressed="false">Show password</button></div>
        </div>
        <label style="display:flex;gap:.65rem;margin-top:1rem"><input name="privacy_consent" type="checkbox" value="1" required><span>I consent to the HOA processing my information for resident verification and community services.</span></label>
        <div class="form-actions"><button class="button button-primary" type="submit">Submit application</button><a href="{{ route('portal.login') }}">Return to login</a></div>
    </form>
</section></main></body></html>
